In [1]:
import pandas as pd

In [2]:
data_path ='/Users/cosmo/Documents/thesis/data/NO2_NO_NH3_freq_meas_data_2021-02-16.xlsx'
raw_response = pd.read_excel(data_path, sheet_name = 1)

In [3]:
raw_response.head()

,NO2 [ppm],50,100,25,50.1,100.1,50.2,100.2,25.1,25.2,...,100.6,25.5,100.7,25.6,50.6,50.7,50.8,25.7,25.8,100.8
0,NO [ppm],100.000000,25.000000,100.000000,25.000000,100.000000,50.000000,25.000000,100.000000,25.000000,...,50.000000,25.00000,25.000000,100.000000,25.000000,50.000000,50.000000,25.000000,50.000000,50.000000
1,NH3 [ppm],25.000000,100.000000,50.000000,100.000000,25.000000,50.000000,50.000000,25.000000,50.000000,...,25.000000,100.00000,25.000000,100.000000,50.000000,100.000000,25.000000,25.000000,50.000000,50.000000
2,1,0.000263,0.000244,0.000259,0.000246,0.000257,0.000243,0.000242,0.000241,0.000244,...,0.000241,0.00024,0.000257,0.000242,0.000258,0.000243,0.000258,0.000245,0.000245,0.000243
3,2,0.000263,0.000244,0.000259,0.000246,0.000257,0.000243,0.000242,0.000241,0.000244,...,0.000241,0.00024,0.000256,0.000242,0.000258,0.000243,0.000257,0.000245,0.000245,0.000243
4,3,0.000263,0.000244,0.000259,0.000247,0.000257,0.000243,0.000242,0.000241,0.000244,...,0.000241,0.00024,0.000256,0.000242,0.000258,0.000243,0.000257,0.000245,0.000245,0.000243